---
title: "SP"
author: "Brian Knaus"
date: "December 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## S & P 2008

```{r, echo=FALSE, results='hide'}
suppressPackageStartupMessages(library(quantmod))
```

```{r}
start <- as.Date("2008-01-01")
end <- as.Date("2008-12-31")

suppressMessages(getSymbols("^GSPC", src = "yahoo", from = start, to = end))
class(GSPC)
head(GSPC)

stocks <- as.xts(data.frame(GSPC = GSPC[,"GSPC.Close"]))

stock_return <- apply(stocks, 1, function(x) {x / stocks[1,]})
stock_return <- as.xts(data.frame(GSPC = stock_return))
stock_return <- (stock_return - 1) * 100

head(stock_return)
```


```{r, echo=FALSE}
candleChart(stock_return, up.col = "black", dn.col = "red", theme = "white")
addSMA(n = c(30, 120))
```




```{r}
getSP <- function(start, end){
  start <- as.Date(start)
  end <- as.Date(end)
  suppressMessages(getSymbols("^GSPC", src = "yahoo", from = start, to = end))
  stocks <- as.xts(data.frame(GSPC = GSPC[,"GSPC.Close"]))
  stock_return <- apply(stocks, 1, function(x) {x / stocks[1,]})
  stock_return <- as.xts(data.frame(GSPC = stock_return))
  stock_return <- (stock_return - 1) * 100

  candleChart(stock_return, up.col = "black", dn.col = "red", theme = "white")
  addSMA(n = c(30, 120))
}
```


## 2008

```{r}
getSP(start = "2008-01-01", end = "2008-12-31")
```


## 2009

```{r}
getSP(start = "2009-01-01", end = "2009-12-31")
```


## 2010

```{r}
getSP(start = "2010-01-01", end = "2010-12-31")
```


## 2011

```{r}
getSP(start = "2011-01-01", end = "2011-12-31")
```


## 2012

```{r}
getSP(start = "2012-01-01", end = "2012-12-31")
```


## 2013

```{r}
getSP(start = "2013-01-01", end = "2013-12-31")
```

## 2014

```{r}
getSP(start = "2014-01-01", end = "2014-12-31")
```


## 2015

```{r}
getSP(start = "2015-01-01", end = "2015-12-31")
```


## 2016

```{r}
getSP(start = "2016-01-01", end = "2016-12-31")
```


## 2017

```{r}
getSP(start = "2017-01-01", end = "2017-12-31")
```


## 2018

```{r}
getSP(start = "2018-01-01", end = "2018-12-31")
```


